version: '2.1'

services:

  api: # Node.js App
    container_name: api
    image: 086256341561.dkr.ecr.us-east-1.amazonaws.com/allways-dev-api:latest
    volumes: # Attach volume local data directory
      - ./api:/home/node
    ports:
      - "3000:3000" # Expose API port
      - "9229:9229" # Expose Node process debug port (disable in production)
    environment: # Set ENV vars
     - NODE_ENV=development
     - PORT=3000
     - DB_URL=mongodb://mongo/allways
     - DB_URL_TEST=mongodb://mongo/allways-test
    restart: always
    links: 
      - database
    depends_on:
      database: # Ensuring that the container will rise only if the database service is healthy
        condition: service_healthy
    
    
  database: # Container for MongoDB
    container_name: mongo
    image: mongo
    volumes: # Attach volume local data directory
      - /home/ec2-user/efs/mongo:/data/db
    ports: # Expose Mongo port
      - "27017:27017"
    restart: always
    healthcheck: # Verifying that the Mongo service was started in the container
      test: ["CMD", "echo", "'db.stats().ok'", "|", "mongo localhost:27017/test --quiet"]
      interval: 30s
      timeout: 10s
      retries: 5

  front-end: #Nginx
    image: 086256341561.dkr.ecr.us-east-1.amazonaws.com/allways-dev-front:latest
    volumes: # Attach volume local data directory
      - ./nginx-homol:/home/nginx-homol
    container_name: nginx-homol
    ports:
      - "80:80"
    environment: # Set variaveis
      - HOME=/app
    restart: always
    links:
      - api
      - bdd-homol

  bdd-homol: # URL para exibir os cenarios de testes (QA)
    image: 086256341561.dkr.ecr.us-east-1.amazonaws.com/allways-bdd:latest
    container_name: bdd-homol
    ports:
      - "4000:4000"
    restart: always
